######################################################################
# Automatically generated by qmake (2.01a) mar feb 21 00:12:34 2012
######################################################################

TEMPLATE = app
QT += network xml
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt warn_on
RESOURCES = icons.qrc

# Input
HEADERS += helper.h \
           myborder.h \
           myicon.h \
           downloadfile.h \
           recordingdialog.h \
           retrievevideourl.h \
           searchbox.h \
           ytdataapi.h \
           ytdelegate.h \
           ytdialog.h \
           yttabbar.h

SOURCES += helper.cpp \
           myborder.cpp \
           myicon.cpp \
           downloadfile.cpp \
           recordingdialog.cpp \
           retrievevideourl.cpp \
           searchbox.cpp \
           ytdataapi.cpp \
           ytdelegate.cpp \
           ytdialog.cpp \
           yttabbar.cpp \
           main.cpp


